image: maven:3.9.9

clone:
  # SonarQube Cloud scanner needs the full history to assign issues properly
  depth: full
definitions:
  caches:
    sonar: ~/.sonar/cache
pipelines:
  branches:
    master:
      - step:
          name: Build and test
          caches:
            - maven
            - sonar
          script:
            - mvn -B -Pit.tidalwave-metrics-v2 -Dtft.profile.metrics.checkstyleGoal= -Dtft.owasp.skip=true
          artifacts:
            - '**/target/**'
